# Generated by Django 6.0.1 on 2026-02-03 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco_instalacao', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Fibra 500MB', max_length=100)),
                ('velocidade_download', models.IntegerField(help_text='Em Mbps')),
                ('velocidade_upload', models.IntegerField(help_text='Em Mbps')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChamadoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEM_CONEXAO', 'Sem Conexão'), ('LENTIDAO', 'Lentidão'), ('FINANCEIRO', 'Dúvida Financeira'), ('MUDANCA_ENDERECO', 'Mudança de Endereço')], max_length=20)),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=1)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Atendimento'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso (Financeiro)'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('ip_fixo', models.GenericIPAddressField(blank=True, help_text='Opcional: IP Fixo do cliente', null=True, protocol='IPv4')),
                ('mac_address', models.CharField(blank=True, help_text='MAC da ONU/Roteador', max_length=17, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='core.cliente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.planointernet')),
            ],
        ),
    ]
